# Generated by Django 5.0.7 on 2024-08-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationsystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationsystem',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reservationsystem',
            name='number_of_people',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], help_text='For bookings greater than 8 people, please call us at 01 23400000.', max_length=5),
        ),
    ]
