# Generated by Django 5.0.7 on 2024-08-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationsystem', '0002_alter_reservationsystem_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationsystem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
